import { AbsenceDay } from '../absenceDays/types';
import { Absence } from '../absences/types';
import { AbsenceType } from '../absenceTypes/types';
import { Department } from '../departments/types';
import { GeneralSetting } from '../generalSettings/types';
import { Project } from '../projects/types';
import { Task } from '../tasks/types';
import { Team } from '../teams/types';
import { TimesheetAccounting } from '../timesheetAccountings/types';
import { TimeTracking } from '../timetrackings/types';
import { User } from '../users/types';
import { UserStatusOverview } from '../userStatusOverview/types';

export type Resources = {
  // absenceBans?: AbsenceBan;
  absenceDays?: AbsenceDay;
  // absenceReplacements?: AbsenceReplacement;
  absences?: Absence;
  absenceTypes?: AbsenceType;
  // changeTimeTrackingRequests?: ChangeTimeTrackingRequest;
  // checkpoints?: Checkpoint;
  // checkpointTrackings?: CheckpointTracking;
  // checkpointTranslations?: CheckpointTranslation;
  // clients?: Client;
  department?: Department;
  generalSettings?: GeneralSetting;
  // holidayRequests?: HolidayRequest;
  // messages?: Message;
  // multiuserToTasks?: MultiuserToTask;
  // nfcTransponder?: NfcTransponder;
  // nodesToUsers?: NodesToUser;
  // notifications?: Notification;
  // notificationsTypeHtml?: NotificationsTypeHtml;
  // notificationUrls?: NotificationUrl;
  // permissionResolveAbsenceTypesAndUsers?: PermissionResolveAbsenceTypesAndUser;
  // permissionResolveDepartments?: PermissionResolveDepartment;
  // permissionResolveHolidayRequests?: PermissionResolveHolidayRequest;
  // permissionResolveQuestions?: PermissionResolveQuestion;
  // permissionResolveTeams?: PermissionResolveTeam;
  // permissionResolveUsers?: PermissionResolveUser;
  // permissions?: Permission;
  projects?: Project;
  // serverEvents?: ServerEvent;
  // serverTime?: ServerTime;
  // skills?: Skill;
  // surveys?: Survey;
  tasks?: Task;
  teams?: Team;
  // timePlannings?: TimePlanning;
  timesheetAccountings?: TimesheetAccounting;
  // timesheetAccountingSummaries?: TimesheetAccountingSummarie;
  // timesheetActionLogs?: TimesheetActionLog;
  // timetrackingChangelogs?: TimetrackingChangelog;
  timeTrackings?: TimeTracking;
  // translations?: Translation;
  users?: User;
  userStatusOverview?: UserStatusOverview;
};
