export type TimePlanning = {
  id: number;
  user_id: number;
  task_id: number;
  scheduling_id: number | null;
  shift_id: number | null;
  recurring_elements_id: number | null;
  department_node_path: string;
  department_id: number;
  department_role_id: number;
  task_node_path: string;
  project_leader_id: number;
  is_nonworking: boolean;
  skill_id: number;
  client_id: number;
  year: number;
  yearmonth: string;
  month: number;
  start_date: string | null;
  start_time: string;
  end_time: string;
  duration: number;
  status: number;
  cost_user: number;
  cost_task: number;
  revenue_user: number;
  revenue_task: number;
  push_trigger: string;
  is_billable: boolean;
  notes: string;
  t_iv_1: string | null;
  t_iv_2: string | null;
  t_iv_3: string | null;
  t_iv_4: string | null;
  t_iv_5: string | null;
  t_iv_6: string | null;
  u_iv_1: string | null;
  u_iv_2: string | null;
  u_iv_3: string | null;
  u_iv_4: string | null;
  u_iv_5: string | null;
  u_iv_6: string | null;
  cost_acc_type: string;
  is_paid_non_working: boolean;
  timestamp_created: boolean | null;
  created_user_id: number;
  created: string | null;
  change_user_id: number | null;
  data_changed: string;
  start_time_timezone: string | null;
  end_time_timezone: string | null;
};
