name: yarn
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install --ignore-engines
      - name: Audit
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: audit --level high
      - name: Lint
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: lint
      - name: Prettycheck
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: prettycheck
      - name: Compile
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: compile
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install --ignore-engines
      - name: Test
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: test
