name: yarn
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          node-version: '14'
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          node-version: '14'
          cmd: audit --level high
      - uses: borales/actions-yarn@v2.0.0
        with:
          node-version: '14'
          cmd: lint
      - uses: borales/actions-yarn@v2.0.0
        with:
          node-version: '14'
          cmd: prettycheck
      - uses: borales/actions-yarn@v2.0.0
        with:
          node-version: '14'
          cmd: compile
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          node-version: '14'
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          node-version: '14'
          cmd: test
