name: yarn
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Audit
        uses: borales/actions-yarn@v4
        with:
          cmd: yarn npm audit --environment production
      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Prettycheck
        uses: borales/actions-yarn@v4
        with:
          cmd: prettycheck
      - name: Compile
        uses: borales/actions-yarn@v4
        with:
          cmd: compile
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Test
        uses: borales/actions-yarn@v4
        with:
          cmd: test
